name: awb

on: [push, pull_request]

jobs:
  build-windows:
    name: Windows
    runs-on: ${{ matrix.windows-version }}
    strategy:
      fail-fast: false
      matrix:
        windows-version: ['windows-latest', 'windows-2016']

    steps:
      - uses: actions/checkout@v2
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.0.2
      - name: Build
        run: |
            MSBuild.exe -m $Env:GITHUB_WORKSPACE\'AutoWikiBrowser no plugins.sln' /p:Configuration=Debug
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.windows-version }}
          path: AWB/bin/Release
      - name: Install Nunit-Console
        run: choco install nunit-console-runner
#      - name: Install Nunit3-Console (doesn't work yet)
#        run: Install-Package NUnit.Runners -Version 3.12.0

      - name: Run Nunit Tests
        run: nunit3-console.exe UnitTests\bin\Debug\UnitTests.dll
        
